### ISSUE TITLE
Add prev and next navigation

### ISSUE THREAD

**Issue by lijhello** [PeterFeicht/cppreference-doc#23]
Hi, Peter

Thanks for this valuable project. It helps me a lot learning C, C++ programming.

Can we add `< prev`, `next >` navigation on each page, so we can read all pages by following the navigation easily, without missing one page.

**Comment by PeterFeicht** [comment]
Thanks for the suggestion. First of all, cppreference.com is, as the name suggests, a reference, and not something you read front to back for learning C++. So for learning the basics you might wanna get a [good C++ book](https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list) instead.

Second, the online version doesn't have such a navigation option. You'd have to add it there, because this offline version is essentially just a snapshot copy of the online version. And then there's also the problem of deciding which is the "next" and "previous" page...

So I'm sorry to say, but the answer is no.
