### ISSUE TITLE
Fetch source by github actions?

### ISSUE THREAD

**Issue by SainoNamkho** [PeterFeicht/cppreference-doc#38]
Repos of other languages of this repo releases less frequently than yours (I really appreciate it for the help your up-to-date offline doc gives me), so I wget from the origin to get the Chinese doc every couple of months. Since the access to cppreference.com is very slow in my region, I tried to write a github action script but have not finished the work.

Are you glad to write the script to auto fetch the source from cppreference.com (maybe with some techniques to avoid duplicate request to the website from forks of this repos) and pack it into docs in github actions? If you don't have time, maybe I'll try to write it when I'm not so busy.

Thanks a lot, wishes.

**Comment by PeterFeicht** [comment]
I haven't used Github actions so far. Since I only release the English version of the archive, I'm not sure how useful that would be.

Feel free to contribute something, maybe even upstream at [p12tic/cppreference-doc](https://github.com/p12tic/cppreference-doc). I'll close this ticket for now, since I don't plan on implementing that myself at this time.
