### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by lijh8** [PeterFeicht/cppreference-doc#41]
Hi, can we have automatically light or dark theme like this?

Thanks!

```
<head>
  <style>
    /* https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme */
    :root {
      color-scheme: light dark
    }
  </style>
</head>
```

**Comment by PeterFeicht** [comment]
I just tried to add it, and it appears that it needs some kind of support from the rest of the stylesheet too because nothing changes. I think this is something that needs to be contributed to the site stylesheet so there is actually a dark style to choose when the browser is set to dark mode.
I don't use dark mode, so feel free to contribute this back to the main site.
